spring:
  application:
    name: Bilyeocho

  datasource:
    url: ${MYSQL_URL}
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    properties:
      hibernate:
        ddl-auto: create

  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}

