#application.yml
spring:
  profiles:
    active: prod

  jpa:
    properties:
      hibernate:
        format_sql: true
        show_sql: true

  data:
    redis:
      timeout: 10000

  aws:
    access:
      key: ${AWS_ACCESS_KEY}
    secret:
      key: ${AWS_SECRET_KEY}
    region: ${AWS_REGION}
    s3:
      bucket: ${S3_BUCKET_NAME}

jwt:
  secret: ${JWT_SECRET}
  refresh-expiration-time: 259200000 # 3days
  access-expiration-time: 3600000
