jwt:
  secret: ${JWT_SECRET}
  refresh-expiration-time: 259200000 # 3days
  access-expiration-time: 3600000

spring:
  application:
    name: Bilyeocho

  datasource:
    url: ${MYSQL_URL}
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        #        ddl-auto: create
        hbm2ddl.auto: create
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
  aws:
    access:
      key: ${AWS_ACCESS_KEY}
    secret:
      key: ${AWS_SECRET_KEY}
    region: ${AWS_REGION}


