#green
version: '3'
services:
  backend:
    build: .
    network_mode: host
    ports:
      - "8082:8080"
    container_name: bilyeocho-green
    environment:
      TZ: "Asia/Seoul"
    env_file:
      - .env