#blue
version: '3'
services:
  backend:
    build: .
    network_mode: host
    ports:
      - "8081:8080"
    container_name: bilyeocho-blue
    environment:
      TZ: "Asia/Seoul"
    env_file:
      - .env